# dsh-plugin-guide skill installer.
# Purpose: copy the KB (excluding generated/local-only parts) into an agent skill directory and verify byte parity.
# Usage:   pwsh -File scripts/install-skill.ps1 -Target <skill-dir> [-Source <kb-root>]
# Scope:   SKILL.md, guide/, references/ (incl. official-docs), scripts/, README*.md, LICENSE, NOTICE.md, CONTRIBUTING.md, SECURITY.md.
# Excluded: downloads/ (generated by scripts), .github/ (CI), .gitignore.
# Target must be the skill directory itself (e.g. ~/.deepseek/skills/dsh-plugin-guide or <project>/.agents/skills/dsh-plugin-guide).
param(
  [Parameter(Mandatory=$true)][string]$Target,
  [string]$Source = ''
)
$ErrorActionPreference = 'Stop'
if (-not $Source) { $Source = Split-Path $PSScriptRoot -Parent }
$src = (Resolve-Path $Source).Path
$top = @('SKILL.md','LICENSE','NOTICE.md','CONTRIBUTING.md','SECURITY.md') + @(Get-ChildItem $src -Filter 'README*.md' -File | ForEach-Object { $_.Name })
$dirs = @('guide','references','scripts')

New-Item -ItemType Directory -Force -Path $Target | Out-Null

foreach ($f in $top) { Copy-Item (Join-Path $src $f) (Join-Path $Target $f) -Force }
foreach ($d in $dirs) {
  # Copy-Item -Recurse into an existing directory would nest the source inside it; replace the owned dir instead.
  $td = Join-Path $Target $d
  if (Test-Path $td) { Remove-Item $td -Recurse -Force }
  Copy-Item (Join-Path $src $d) $td -Recurse -Force
}

# Prune target files under the owned scope that no longer exist in the source (keeps reinstalls clean).
foreach ($d in $dirs) {
  $td = Join-Path $Target $d
  if (Test-Path $td) {
    $sd = Join-Path $src $d
    $sRoot = (Resolve-Path $sd).Path
    $tRoot = (Resolve-Path $td).Path
    Get-ChildItem -Recurse -File $td | ForEach-Object {
      $rel = $_.FullName.Substring($tRoot.Length + 1)
      if (-not (Test-Path (Join-Path $sRoot $rel))) { Remove-Item $_.FullName -Force }
    }
  }
}
Get-ChildItem $Target -File -ErrorAction SilentlyContinue | ForEach-Object {
  if (($_.Name -like 'README*.md' -or $top -contains $_.Name) -and -not (Test-Path (Join-Path $src $_.Name))) { Remove-Item $_.FullName -Force }
}

# Parity report: every scoped source file must exist in the target byte-for-byte.
$checked = 0; $mismatch = 0
foreach ($f in $top) {
  $s = Join-Path $src $f; $t = Join-Path $Target $f
  if (Test-Path $t) { $checked++; if ((Get-FileHash $s -Algorithm MD5).Hash -ne (Get-FileHash $t -Algorithm MD5).Hash) { $mismatch++; Write-Output "MISMATCH: $f" } }
  else { $mismatch++; Write-Output "MISSING-TARGET: $f" }
}
foreach ($d in $dirs) {
  $sd = Join-Path $src $d
  $sRoot = (Resolve-Path $sd).Path
  Get-ChildItem -Recurse -File $sd | ForEach-Object {
    $rel = $_.FullName.Substring($sRoot.Length + 1)
    $t = Join-Path (Join-Path $Target $d) $rel
    if (Test-Path $t) { $checked++; if ((Get-FileHash $_.FullName -Algorithm MD5).Hash -ne (Get-FileHash $t -Algorithm MD5).Hash) { $mismatch++; Write-Output "MISMATCH: $d\$rel" } }
    else { $mismatch++; Write-Output "MISSING-TARGET: $d\$rel" }
  }
}
Write-Output "DONE: $checked scoped files verified, $mismatch mismatches -> $Target"
if ($mismatch -gt 0) { exit 1 }
exit 0
